### PR TITLE
User-facing documentation

### PR DESCRIPTION
**Pull request by krassowski**
Add user guide describing how to use the extension.

### CODE REVIEW

**Comment by krassowski** [comment]
please update playwright snapshots

**Comment by krassowski** [comment]
please update playwright snapshots

**Comment by krassowski** [comment]
please update playwright snapshots

**Comment by krassowski** [comment]
please update playwright snapshots

**Comment by krassowski** [comment]
please update playwright snapshots

**Comment by fcollonval** [comment]
@krassowski could you try rebasing the branch before triggering the snapshots update?
In this PR diff I don't see the missing `test:update` you added in the main branch.

**Comment by krassowski** [comment]
Thanks for the suggestion!

**Comment by krassowski** [comment]
please update playwright snapshots

**Comment by krassowski** [comment]
please update playwright snapshots

**Comment by krassowski** [comment]
please update playwright snapshots

**Pull request merged**
